#!/usr/bin/env python
"""Regenerate fickling/stdlib_names.py.

The checked-in table must cover the union of top-level stdlib module names
across every Python version fickling supports, because the scanner cannot
know in advance which interpreter will load the pickle it is analyzing (a
CI job may scan a pickle that later executes on a developer's machine).

Run from the repository root with uv available:

    uv run --no-project python scripts/generate_stdlib_names.py

The script shells out to each supported interpreter via ``uv`` and merges
their ``sys.stdlib_module_names`` into per-version frozensets plus the
union that ships as the default.
"""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

SUPPORTED_PYTHONS = ["3.10", "3.11", "3.12", "3.13", "3.14"]

OUTPUT = Path(__file__).parent.parent / "fickling" / "stdlib_names.py"

HEADER = '''"""Top-level standard-library module names across supported Pythons.

Generated by scripts/generate_stdlib_names.py — do not edit by hand;
regenerate instead. Last generated {generated}.

Why a checked-in table instead of ``sys.stdlib_module_names`` alone: the
pickle being scanned is not necessarily loaded by the interpreter doing
the scanning (imagine a CI job gating artifacts for developer machines).
A module that exists in *any* supported Python version must therefore be
treated as potentially-standard, or benign pickles get flagged whenever
the scanner runs on a different version than the loader.

Default semantics: ``STDLIB_MODULE_NAMES`` is the union of every listed
version plus the running interpreter's own names, so a scanner can never
miss names from a Python newer than this table. The residual risk of
this union — a removed module name (``imp``, ``asynchat``, …) squatted
by a malicious PyPI distribution on newer interpreters — is inherent to
static analysis without knowing the target version; callers who know
exactly which interpreter will unpickle may narrow the set with
:func:`use_stdlib_of`.
"""

from __future__ import annotations

import sys

__all__ = [
    "PYTHON_VERSIONS",
    "STDLIB_MODULE_NAMES",
    "STDLIB_MODULE_NAMES_BY_VERSION",
    "current_shadowed_names",
    "use_stdlib_of",
]


'''


def collect(version: str) -> list[str]:
    result = subprocess.run(
        [
            "uv",
            "run",
            "--no-project",
            "-p",
            version,
            "python",
            "-c",
            "import json, sys; print(json.dumps(sorted(sys.stdlib_module_names)))",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    by_version: dict[str, list[str]] = {}
    for version in SUPPORTED_PYTHONS:
        by_version[version] = collect(version)

    union: set[str] = set()
    for names in by_version.values():
        union |= set(names)

    lines = [HEADER.format(generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))]
    lines.append(f"PYTHON_VERSIONS = {SUPPORTED_PYTHONS!r}\n")
    lines.append("STDLIB_MODULE_NAMES_BY_VERSION: dict[str, frozenset[str]] = {")
    for version in SUPPORTED_PYTHONS:
        names = ", ".join(repr(n) for n in by_version[version])
        lines.append(f"    {version!r}: frozenset({{{names}}}),")
    lines.append("}\n")
    latest = SUPPORTED_PYTHONS[-1]
    # Only public top-level names: underscore-prefixed entries differ across
    # platform builds without being real removals, and imports of private
    # stdlib modules are already surfaced separately.
    shadowed = sorted(
        n for n in (union - set(by_version[latest])) if not n.startswith("_")
    )
    lines.append(
        "# Names stdlib somewhere in the support matrix but absent from the\n"
        f"# newest listed release ({latest}): removable dead batteries plus\n"
        "# future-only additions. On interpreters lacking them these names can\n"
        "# be shadowed by third-party PyPI packages, so imports are surfaced by\n"
        "# the ShadowedStdlibImports analysis instead of being trusted.\n"
    )
    names = ", ".join(repr(n) for n in shadowed)
    lines.append(f"SHADOWED_STDLIB_MODULE_NAMES: frozenset[str] = frozenset({{{names}}})\n")

    text = "\n".join(lines)
    # Append runtime augmentation and override API verbatim (not regenerated).
    text += '''
_SELECTED_VERSIONS: tuple[str, ...] | None = None

STDLIB_MODULE_NAMES_UNION: frozenset[str] = frozenset().union(
    *STDLIB_MODULE_NAMES_BY_VERSION.values()
)


def _compute_default_stdlib() -> frozenset[str]:
    """Union the table with the running interpreter's own stdlib names."""
    return STDLIB_MODULE_NAMES_UNION | sys.stdlib_module_names


STDLIB_MODULE_NAMES: frozenset[str] = _compute_default_stdlib()


def current_shadowed_names() -> frozenset[str]:
    """Names that are not stdlib under the currently selected target(s).

    Default (no :func:`use_stdlib_of` selection): names absent from the
    newest supported release. With a selection: names absent from *every*
    selected version, so known-good targets stop warning about names they
    genuinely ship.
    """
    if _SELECTED_VERSIONS is None:
        return SHADOWED_STDLIB_MODULE_NAMES
    present: set[str] = set()
    for version in _SELECTED_VERSIONS:
        present |= STDLIB_MODULE_NAMES_BY_VERSION[version]
    return SHADOWED_STDLIB_MODULE_NAMES - present


def use_stdlib_of(*versions: str) -> frozenset[str]:
    """Restrict the effective stdlib name set to specific Python versions.

    For scanners that know exactly which interpreter will unpickle the
    target file, narrowing avoids treating removed-and-possibly-squatted
    names as standard. Pass no arguments to restore the default union.
    Unknown versions raise ``KeyError``.
    """
    global STDLIB_MODULE_NAMES, _SELECTED_VERSIONS
    if not versions:
        _SELECTED_VERSIONS = None
        STDLIB_MODULE_NAMES = _compute_default_stdlib()
    else:
        unknown = [v for v in versions if v not in STDLIB_MODULE_NAMES_BY_VERSION]
        if unknown:
            raise KeyError(
                f"Unsupported Python versions {unknown}; "
                f"known: {sorted(STDLIB_MODULE_NAMES_BY_VERSION)}"
            )
        _SELECTED_VERSIONS = tuple(versions)
        STDLIB_MODULE_NAMES = frozenset().union(
            *(STDLIB_MODULE_NAMES_BY_VERSION[v] for v in versions)
        )
    return STDLIB_MODULE_NAMES
'''

    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT}")
    print(f"union size: {len(union)}")


if __name__ == "__main__":
    main()
